var namespace_coursework =
[
    [ "Properties", "namespace_coursework_1_1_properties.html", "namespace_coursework_1_1_properties" ],
    [ "AdminPopup", "class_coursework_1_1_admin_popup.html", "class_coursework_1_1_admin_popup" ],
    [ "Categories", "class_coursework_1_1_categories.html", "class_coursework_1_1_categories" ],
    [ "CoolButton", "class_coursework_1_1_cool_button.html", null ],
    [ "dragAndDrop", "class_coursework_1_1drag_and_drop.html", "class_coursework_1_1drag_and_drop" ],
    [ "Home", "class_coursework_1_1_home.html", "class_coursework_1_1_home" ],
    [ "Leaderboard", "class_coursework_1_1_leaderboard.html", "class_coursework_1_1_leaderboard" ],
    [ "Login", "class_coursework_1_1_login.html", "class_coursework_1_1_login" ],
    [ "multipleChoice", "class_coursework_1_1multiple_choice.html", "class_coursework_1_1multiple_choice" ],
    [ "player", "class_coursework_1_1player.html", null ],
    [ "Profiles", "class_coursework_1_1_profiles.html", "class_coursework_1_1_profiles" ],
    [ "Prompt", "class_coursework_1_1_prompt.html", "class_coursework_1_1_prompt" ],
    [ "QuestionData", "class_coursework_1_1_question_data.html", null ],
    [ "questionInfo", "class_coursework_1_1question_info.html", null ],
    [ "Quiz_Type", "class_coursework_1_1_quiz___type.html", "class_coursework_1_1_quiz___type" ],
    [ "Ready", "class_coursework_1_1_ready.html", "class_coursework_1_1_ready" ],
    [ "Register", "class_coursework_1_1_register.html", "class_coursework_1_1_register" ],
    [ "RegisterPFP", "class_coursework_1_1_register_p_f_p.html", "class_coursework_1_1_register_p_f_p" ],
    [ "Results", "class_coursework_1_1_results.html", "class_coursework_1_1_results" ],
    [ "Splashscreen", "class_coursework_1_1_splashscreen.html", "class_coursework_1_1_splashscreen" ],
    [ "timeKeeper", "class_coursework_1_1time_keeper.html", null ],
    [ "TrueFalse", "class_coursework_1_1_true_false.html", "class_coursework_1_1_true_false" ],
    [ "Written", "class_coursework_1_1_written.html", "class_coursework_1_1_written" ]
];