.TH "Coursework.CoolButton" 3 "Version final" "coursework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coursework.CoolButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits Button\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPaint\fP (System\&.Windows\&.Forms\&.PaintEventArgs e)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for coursework from the source code\&.
