.TH "Coursework.Categories" 3 "Version final" "coursework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coursework.Categories
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCategories\fP (\fBplayer\fP activePassthrough, string difficultyPassthrough)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBplayer\fP \fBactivePlayer\fP"
.br
.ti -1c
.RI "static string \fBDifficulty\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void Coursework\&.Categories\&.Dispose (bool disposing)\fR [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for coursework from the source code\&.
