.TH "Coursework.player" 3 "Version final" "coursework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coursework.player
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBplayer\fP (string name, string pass)"
.br
.ti -1c
.RI "void \fBAccumulativeReset\fP ()"
.br
.ti -1c
.RI "void \fBAccumulate\fP ()"
.br
.ti -1c
.RI "void \fBCreateDatabaseForPlayer\fP ()"
.br
.ti -1c
.RI "void \fBAddToDatabase\fP ()"
.br
.ti -1c
.RI "void \fBUpdateScoresBinFile\fP (int newScore, string mode)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBusername\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBpassword\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBcurrentScore\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBtopWildScore\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBtopBaseScore\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "char \fBdefaultPFP\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Image \fBProfilePicture\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBrunCount\fP\fR [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for coursework from the source code\&.
