.TH "Coursework.Profiles" 3 "Version final" "coursework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coursework.Profiles
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProfiles\fP (\fBplayer\fP activePassthrough)"
.br
.ti -1c
.RI "void \fBLoadDataFromCsv\fP ()"
.br
.ti -1c
.RI "void \fBSaveDataToCsv\fP ()"
.br
.ti -1c
.RI "void \fBEditEnable\fP ()"
.br
.ti -1c
.RI "string \fBGetPasswordFromCsv\fP (string username)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DataGridView \fBprofileGrid\fP"
.br
.ti -1c
.RI "\fBCoolButton\fP \fBSubmit\fP"
.br
.ti -1c
.RI "PictureBox \fBeditEnable\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void Coursework\&.Profiles\&.Dispose (bool disposing)\fR [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for coursework from the source code\&.
