.TH "Coursework.timeKeeper" 3 "Version final" "coursework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coursework.timeKeeper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBPlaySound\fP ()"
.br
.ti -1c
.RI "void \fBStop\fP ()"
.br
.ti -1c
.RI "int \fBGetRemainingTimeInSeconds\fP ()"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler \fBTimeUp\fP"
.br
.ti -1c
.RI "EventHandler< int > \fBTimeUpdated\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for coursework from the source code\&.
