.TH "Coursework" 3 "Version final" "coursework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coursework
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAdminPopup\fP"
.br
.ti -1c
.RI "class \fBCategories\fP"
.br
.ti -1c
.RI "class \fBCoolButton\fP"
.br
.ti -1c
.RI "class \fBdragAndDrop\fP"
.br
.ti -1c
.RI "class \fBHome\fP"
.br
.ti -1c
.RI "class \fBLeaderboard\fP"
.br
.ti -1c
.RI "class \fBLogin\fP"
.br
.ti -1c
.RI "class \fBmultipleChoice\fP"
.br
.ti -1c
.RI "class \fBplayer\fP"
.br
.ti -1c
.RI "class \fBProfiles\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBPrompt\fP"
.br
.ti -1c
.RI "class \fBQuestionData\fP"
.br
.ti -1c
.RI "class \fBquestionInfo\fP"
.br
.ti -1c
.RI "class \fBQuiz_Type\fP"
.br
.ti -1c
.RI "class \fBReady\fP"
.br
.ti -1c
.RI "class \fBRegister\fP"
.br
.ti -1c
.RI "class \fBRegisterPFP\fP"
.br
.ti -1c
.RI "class \fBResults\fP"
.br
.ti -1c
.RI "class \fBscoreGenerator\fP"
.br
.ti -1c
.RI "class \fBSplashscreen\fP"
.br
.ti -1c
.RI "class \fBtimeKeeper\fP"
.br
.ti -1c
.RI "class \fBTrueFalse\fP"
.br
.ti -1c
.RI "class \fBWritten\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for coursework from the source code\&.
