.TH "Coursework.questionInfo" 3 "Version final" "coursework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coursework.questionInfo
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBtype\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBdifficulty\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBcategory\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBquestion\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBcorrect_answer\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "List< string > \fBincorrect_answers\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBquestionNo\fP\fR [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for coursework from the source code\&.
